### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{40e612c0 position=2 id=-1, oldPos=-1, pLpos:-1 no parent}

### ISSUE THREAD

**Issue by mshearer123** [wasabeef/recyclerview-animators#12]
crash on android 4.0.4 

after adding item and calling notifyItemMoved.  
flinging recyclerview crashes app.

java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{40e612c0 position=2 id=-1, oldPos=-1, pLpos:-1 no parent}
       at android.support.v7.widget.RecyclerView$4.attachViewToParent(RecyclerView.java:377)
       at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:208)
       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:4936)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:4913)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:4901)
       at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1340)
       at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:584)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:925)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1486)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1399)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11425)
       at android.view.ViewGroup.layout(ViewGroup.java:4232)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1509)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2498)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4944)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by hbb20** [comment]
Can you show the code?

**Comment by mshearer123** [comment]
Hi,

Sorry I can't,  I put together a sample app to show the crash, but it does happen so I guess something else is going on in our code.

**Comment by rjrjr** [comment]
Related, with a repro case. Can't promise it's the same issue, but the symptom is the same.

https://code.google.com/p/android/issues/detail?id=172416

**Comment by ypresto** [comment]
Smooth scrolling before animation finishes randomly causes this crash.

**Comment by xiong-it** [comment]
I add a headview for RecyclerView and use notifyItemRangeChanged(0, mDatas.size()) in adapter,this problem appeared. finally, I fixed it by change notifyItemRangeChanged(0, mDatas.size()) to notifyItemRangeChanged(1, mDatas.size()), it worked fine.

**Comment by swkfx** [comment]
@xiong-it thanks

**Comment by indiascope** [comment]
I also use header with Recyclerview. when i app item at 1 position because at 0 position header is present but when i add item at 1 position .i get new data added at 2 position instead of 1 position in recyclerview. so i try to add item at  0 position and notifyItemRangeChanged to start from 1. still my app crash.

if (!userInfoList.contains(peopleDetailInfo)) {
            userInfoList.add(0,peopleDetailInfo);
            notifyItemInserted(0);
            notifyItemRangeChanged(1,userInfoList.size());
        }

**Comment by bradroid** [comment]
@ypresto Hello, I can see that your fix is included in library version 2.2.6, but I'm using version 2.2.7 of the library and can still reproduce this issue.
I'm not using any headers or footers, just a homogeneous list.
When replacing data, I always clear all the items like this in my adapter:

```
  data.clear();
  data.addAll(newData);
```
Where data is a List of items.
I do use `smoothScrollToPosition` after updating the items.

I also use DiffUtil to calculate changes in my adapter and usually, everything works fine, but in very rare cases it crashes with `java.lang.IllegalArgumentException: Called attach on a child which is not detached`. I have no how to reproduce it, I only see a few % of users getting this on my crash reporting tool.
